app.name: "UNCHAINED CMS"
#site_url: "https://wherever-you-want-to-run-your-cms"
languages:
  default: "Deutsch"
groups:
  author:
    cockpit:
      finder: false
      backend: true
    collections:
      manage: true
    singletons:
      manage: true
#responseCache:
#  duration: 60
